;;; Automatically generated by ‘recentf’ on Fri Jun 16 13:30:57 2023.

(setq recentf-list
      '(
        "~/.emacs.d/.gitignore"
        "~/.emacs.d/emacs-config.org"
        "~/open_side.sh"
        "~/.emacs.d/README.en.org"
        "~/.emacs.d/README.org"
        "~/.emacs.d/README.en.html"
        "~/.emacs.d/README.en.md"
        "~/.emacs.d/README.html"
        "~/.emacs.d/README.md"
        "~/.emacs.d/README.zh.md"
        "~/Code/Python/Beluck/main.py"
        "~/org/ai.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
