;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by â€˜savehistâ€™.

(setq savehist-minibuffer-history-variables '(org-link--history swiper-history counsel-M-x-history ef-themes--select-theme-history minibuffer-history markdown-gfm-language-history pyvenv-workon-history ivy-history org-roam-node-history org-read-date-history file-name-history buffer-name-history extended-command-history consult--buffer-history consult--line-history empty-history))
(setq counsel-M-x-history '(#("^shell" 0 6 (ivy-index 6)) "shell" "shell" #("^package-list" 0 13 (ivy-index 0)) "package-list-packages"))
(setq ef-themes--select-theme-history '(#("ef-winter" 0 9 (ivy-index 0))))
(setq pyvenv-workon-history '(#("pyqt6" 0 5 (ivy-index 2))))
(setq ivy-history '(#("*Messages*" 0 10 (ivy-index 3)) #("rime-ice" 0 8 (ivy-index 0)) #("imgs/rime.png" 0 13 (ivy-index 0)) #("org mode" 0 8 (ivy-index 0)) #("imgs/org.png" 0 12 (ivy-index 0)) #("dashband" 0 8 (ivy-index 0)) #("imgs/dashband.png" 0 17 (ivy-index 0)) #("å°é¹¤åŒæ‹¼" 0 4 (ivy-index 2 idx 2)) #("è‡ªç„¶ç åŒæ‹¼" 0 5 (ivy-index 1 idx 1)) #("pyright-langserver" 0 18 (ivy-index 1))))
(setq org-read-date-history '("   "))
(setq file-name-history '("~/.emacs.d/.gitignore" "~/open_side.sh" "~/.emacs.d/README.org" "~/.emacs.d/README.en.org" "~/.emacs.d/README.org" "~/.emacs.d/.gitignore" "~/.emacs.d/emacs-config.org" "~/.emacs.d/README.md" "~/.emacs.d/README.en.md" #("/home/elon/.emacs.d/README.md" 0 29 (ivy-index 1)) "~/.emacs.d/README.en.md" "~/.emacs.d/README.en.md" "~/.emacs.d/.gitignore" "~/.emacs.d/README.md" #("/home/elon/.emacs.d/README.zh.md" 0 32 (ivy-index 0)) "~/.emacs.d/README.md" "~/.emacs.d/.gitignore" "~/Code/Python/Beluck/main.py" #("/home/elon/org/ai.org" 0 21 (ivy-index 7)) "~/.emacs.d/emacs-config.org"))
(setq buffer-name-history '("*Messages*" #("*eshell*" 0 8 (ivy-index 0)) #("*shell*" 0 7 (ivy-index 0)) "*Messages*" "emacs-config.org" "*dashboard*" "*Messages*" "*Messages*"))
(setq extended-command-history '("auto-package-update-now" "package-list-packages" "comment-line" "org-toggle-inline-images" "org-display-inline-images" "org-insert-link" "comment-region" "package-list-packages" "consult-buffer" #("savehist-mode" 0 13 (ivy-index 1)) #("package-list-packages" 0 21 (ivy-index 1)) #("auto-package-update-now" 0 23 (ivy-index 1)) #("package-refresh-contents" 0 24 (ivy-index 0)) #("restart-emacs" 0 13 (ivy-index 3)) #("ef-themes-select" 0 16 (ivy-index 3)) #("markdown-live-preview-switch-to-output" 0 38 (ivy-index 0)) #("markdown-insert-image" 0 21 (ivy-index 0)) #("rime-select-schema" 0 18 (ivy-index 0)) #("org-download-clipboard" 0 22 (ivy-index 0)) #("rime-mode" 0 9 (ivy-index 0)) #("markdown-edit-code-block" 0 24 (ivy-index 3)) #("markdown-insert-gfm-code-block" 0 30 (ivy-index 2)) #("markdown-toggle-fontify-code-blocks-natively" 0 44 (ivy-index 1)) #("markdown-insert-code" 0 20 (ivy-index 0)) #("markdown-insert-uri" 0 19 (ivy-index 0)) #("eglot" 0 5 (ivy-index 9)) #("pyvenv-workon" 0 13 (ivy-index 5)) #("pyvenv-mode" 0 11 (ivy-index 3)) #("lsp" 0 3 (ivy-index 126)) #("org-time-stamp" 0 14 (ivy-index 1)) #("org-babel-tangle" 0 16 (ivy-index 1)) #("eshell" 0 6 (ivy-index 7)) #("uncomment-region" 0 16 (ivy-index 2)) #("comment-region" 0 14 (ivy-index 1))))
(setq consult--buffer-history '(#("*Messages*øˆ€€‚" 0 10 (ivy-index 2 face consult-buffer multi-category (buffer . "*Messages*")) 10 11 (ivy-index 2 invisible t consult-strip t)) #("emacs-config.orgøˆ€€‚" 0 16 (ivy-index 1 face consult-buffer multi-category (buffer . "emacs-config.org")) 16 17 (ivy-index 1 invisible t consult-strip t)) #("*dashboard*øˆ€€‚" 0 11 (multi-category (buffer . "*dashboard*") face consult-buffer ivy-index 0) 11 12 (consult-strip t invisible t ivy-index 0))))
(setq consult--line-history '("lv" "markdown-mode" "ht" "chat" "cape" "corfu" "consult-buffer" "savehist
** savehistè®°ä½è¿·ä½ ç¼“å†²åŒºå†å²øˆ€‹ƒ
(use-package savehistøˆ€‹‡
  :hook (after-init . savehist-mode)øˆ€‹‰
  (setq savehist-additional-variables '(mark-ringøˆ€‹
  (setq savehist-autosave-interval 300))øˆ€‹“" "savehist
  (setq savehist-autosave-interval 300))øˆ€‹“
(use-package savehistøˆ€¤¡
  (savehist-mode))øˆ€¤£
** savehistè®°ä½è¿·ä½ ç¼“å†²åŒºå†å²øˆ€‹ƒ
(use-package savehistøˆ€‹‡
  :hook (after-init . savehist-mode)øˆ€‹‰
  (setq savehist-additional-variables '(mark-ringøˆ€‹" "savehi
** savehistè®°ä½è¿·ä½ ç¼“å†²åŒºå†å²øˆ€‹ƒ
(use-package savehistøˆ€‹‡
  :hook (after-init . savehist-mode)øˆ€‹‰
  (setq savehist-additional-variables '(mark-ringøˆ€‹
  (setq savehist-autosave-interval 300))øˆ€‹“
(use-package savehistøˆ€¤¡
  (savehist-mode))øˆ€¤£" "theme
    (ef-themes-load-random 'dark))øˆ€ƒ˜
   consult-theme :preview-key '(:debounce 0.2 any)øˆ€¦›
  (org-roam-ui-sync-theme t)øˆ€²‚
  (eshell-git-prompt-use-theme 'multiline2)øˆ€¸
[[https://protesilaos.com/emacs/ef-themes][ef themes]] æ˜¯æˆ‘éå¸¸å–œæ¬¢çš„ä¸€ä¸ªä¸»é¢˜åŒ…ã€‚øˆ€‚¹
(use-package ef-themesøˆ€‚¼
  :bind (\"C-c t\" . ef-themes-toggle)øˆ€‚¾
  ;; set two specific themes and switch between themøˆ€ƒ€
  (setq ef-themes-to-toggle '(ef-summer ef-winter))øˆ€ƒ" "theme
  (mapc #'disable-theme custom-enabled-themes)øˆ€ƒŒ
  ;; Load the theme of choice:øˆ€ƒ
  ;; The themes we provide are recorded in the `ef-themes-dark-themes',øˆ€ƒ
  ;; `ef-themes-light-themes'.øˆ€ƒ
  ;; (ef-themes-select 'ef-summer)øˆ€ƒ“
      (ef-themes-load-random)øˆ€ƒ—
    (ef-themes-load-random 'dark))øˆ€ƒ˜
   consult-theme :preview-key '(:debounce 0.2 any)øˆ€¦›
  (org-roam-ui-sync-theme t)øˆ€²‚" "auto-package
  auto-package-update            20211108.2025  available    melpa    Automatically update Emacs packages.øˆ€ƒ¾" "theme
  (eshell-git-prompt-use-theme 'multiline2)øˆ€¸™
[[https://protesilaos.com/emacs/ef-themes][ef themes]] æ˜¯æˆ‘éå¸¸å–œæ¬¢çš„ä¸€ä¸ªä¸»é¢˜åŒ…ã€‚øˆ€‚¹
(use-package ef-themesøˆ€‚¼
  :bind (\"C-c t\" . ef-themes-toggle)øˆ€‚¾
  ;; set two specific themes and switch between themøˆ€ƒ€
  (setq ef-themes-to-toggle '(ef-winter ef-summer))øˆ€ƒ
  (setq ef-themes-headingsøˆ€ƒƒ
  (setq ef-themes-region '(intense no-extend neutral))øˆ€ƒŠ
  ;; Disable all other themes to avoid awkward blending:øˆ€ƒ‹" "theme
  (org-roam-ui-sync-theme t)øˆ€²‚
  (eshell-git-prompt-use-theme 'multiline2)øˆ€¸™
[[https://protesilaos.com/emacs/ef-themes][ef themes]] æ˜¯æˆ‘éå¸¸å–œæ¬¢çš„ä¸€ä¸ªä¸»é¢˜åŒ…ã€‚øˆ€‚¹
(use-package ef-themesøˆ€‚¼
  :bind (\"C-c t\" . ef-themes-toggle)øˆ€‚¾
  ;; set two specific themes and switch between themøˆ€ƒ€
  (setq ef-themes-to-toggle '(ef-winter ef-summer))øˆ€ƒ
  (setq ef-themes-headingsøˆ€ƒƒ
  (setq ef-themes-region '(intense no-extend neutral))øˆ€ƒŠ" "(corfu-cycle t)
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'øˆ€§ƒ" "pyven
** pyvenvøˆ€³Š
(use-package pyvenv)øˆ€³Œ" "eglot
  eglot                          1.15           available    gnu      The Emacs Client for LSP serversøˆ€• 
  eglot                          1.15.0.20230609.11219 available    gnu-devel The Emacs Client for LSP serversøˆ€•¡
  eglot-fsharp                   20230324.1942  available    melpa    fsharp-mode eglot integrationøˆ€•¢
  eglot-java                     20230213.218   available    melpa    Java extension for the eglot LSP clientøˆ€•£
  eglot-jl                       20230601.1335  available    melpa    Julia support for eglotøˆ€•¤
  flycheck-eglot                 20230202.1844  available    melpa    Flycheck support for eglotøˆ€”
  consult-eglot                  20230423.1505  available    melpa    A consulting-read interface for eglotøˆ€—" "eglot
  consult-eglot                  20230423.1505  available    melpa    A consulting-read interface for eglotøˆ€ŒŸ
  eglot                          1.15           available    gnu      The Emacs Client for LSP serversøˆ€”
  eglot-fsharp                   20230324.1942  available    melpa    fsharp-mode eglot integrationøˆ€”‚
  eglot-java                     20230213.218   available    melpa    Java extension for the eglot LSP clientøˆ€”ƒ
  eglot-jl                       20230601.1335  available    melpa    Julia support for eglotøˆ€”„
  flycheck-eglot                 20230202.1844  available    melpa    Flycheck support for eglotøˆ€œ" "elpa.
  :quelpa (sdcv :fetcher github :repo \"manateelazycat/sdcv\")øˆ€°„
  :quelpa (rime :fetcher githubøˆ€²²
	  '((\"melpa\"  . \"https://melpa.org/packages/\")øˆ€‰
	    (\"gnu\"    . \"https://elpa.gnu.org/packages/\")øˆ€Š
	    (\"nongnu\" . \"https://elpa.nongnu.org/nongnu/\")))øˆ€‹
** quelpaåŒ…ç®¡ç†å™¨øˆ€®
[[https://github.com/quelpa/quelpa][quelpa]] æ˜¯é…åˆ =package.el= ä½¿ç”¨çš„ï¼ŒåŸºäºgitçš„ä¸€ä¸ªåŒ…ç®¡ç†å™¨ã€‚øˆ€¯
;; å®‰è£… `quelpa'øˆ€±
(use-package quelpaøˆ€²" "elpa
  :quelpa (sdcv :fetcher github :repo \"manateelazycat/sdcv\")øˆ€°„
  :quelpa (rime :fetcher githubøˆ€²²
	  '((\"melpa\"  . \"https://melpa.org/packages/\")øˆ€‰
	    (\"gnu\"    . \"https://elpa.gnu.org/packages/\")øˆ€Š
	    (\"nongnu\" . \"https://elpa.nongnu.org/nongnu/\")))øˆ€‹
** quelpaåŒ…ç®¡ç†å™¨øˆ€®
[[https://github.com/quelpa/quelpa][quelpa]] æ˜¯é…åˆ =package.el= ä½¿ç”¨çš„ï¼ŒåŸºäºgitçš„ä¸€ä¸ªåŒ…ç®¡ç†å™¨ã€‚øˆ€¯
;; å®‰è£… `quelpa'øˆ€±
(use-package quelpaøˆ€²" "all-to
  (org-habit-show-all-today t)øˆ€£" "comple
    (require 'init-completion)            ; è¡¥å…¨ç³»ç»Ÿøˆ€‚˜
        '(\"*Completions*\"øˆ€Š
          \"*Fuzzy Completions*\"øˆ€Š„
  (org-outline-path-complete-in-steps nil)øˆ€”¿
                               (setq-local org-complete-tags-always-offer-all-agenda-tags t)))øˆ€—–
* init-completion.eløˆ€£¯
:HEADER-ARGS: :tangle lisp/init-completion.el :mkdirp yesøˆ€£±
** init-completion.el æ–‡ä»¶å¤´øˆ€£¶
;;; init-completion.el --- Completion settings -*- lexical-binding: t -*-øˆ€£¸" "pyve
** pyvenvøˆ€²¶
(use-package pyvenv)øˆ€²¸" "9998
					(\"#+begin_src\"      . 9998)         ; âœøˆ€‘¶" "org-ai
** org-aiæ™ºèƒ½åŠ©æ‰‹øˆ€°º
[[https://github.com/rksm/org-ai][org-ai]] æ’ä»¶å¯ä»¥è®¿é—® ChatGPT å¹¶æˆä¸º Emacs çš„æ™ºèƒ½åŠ©æ‰‹ã€‚øˆ€°¼
(use-package org-aiøˆ€°¿
         (\"C-c q\" . org-ai-prompt)øˆ€±‚
         (\"C-c x\" . org-ai-on-region)øˆ€±ƒ
  :hook (org-mode . org-ai-mode)øˆ€±…
  ;; (setq org-ai-openai-api-token \"Your Key\") ; ä»¥æ˜æ–‡çš„æ–¹å¼å­˜å‚¨keyï¼Œæˆ–è€…æ”¾å…¥åˆ° ~/.authinfo.gpg æ–‡ä»¶é‡Œøˆ€±‡
  (setq org-ai-default-max-tokens 480)øˆ€±ˆ
  (setq org-ai-default-chat-system-prompt \"ä½ æ˜¯ä¸€ä¸ªEmacsåŠ©æ‰‹ï¼Œè¯·ä»¥Org-modeçš„æ ¼å¼æ¥å›å¤æˆ‘\")øˆ€±‰" "all-the-icons
(use-package all-the-iconsøˆ€ˆ¦
  :commands all-the-icons-install-fontsøˆ€ˆ©
** all-the-iconsøˆ€Š
(use-package all-the-iconsøˆ€Š
      (setq dashboard-icon-type 'all-the-icons)øˆ€Š¡
** all-the-icons-completionè¡¥å…¨å›¾æ ‡ç¾åŒ–øˆ€©Ÿ
(use-package all-the-icons-completionøˆ€©¡
  :hook ((after-init . all-the-icons-completion-mode)øˆ€©£
         (marginalia-mode . all-the-icons-completion-marginalia-setup))øˆ€©¤" "minibuffer
        '((minibuffer . nil)))øˆ€ˆ
  ;; Allow commands in minibuffers, will affect `dired-do-dired-do-find-regexp-and-replace' command:øˆ€‹
  (setq enable-recursive-minibuffers t)øˆ€‹
    :bind (:map minibuffer-local-mapøˆ€¤“
                (\"M-<DEL>\" . my/minibuffer-backward-kill)øˆ€¤”
    (defun my/minibuffer-backward-kill (arg)øˆ€¤˜
      \"When minibuffer is completing a file name delete up to parentøˆ€¤™
      (if minibuffer-completing-file-nameøˆ€¤œ
          (if (string-match-p \"/.\" (minibuffer-contents))øˆ€¤" "ef-summer
  (setq ef-themes-to-toggle '(ef-winter ef-summer))øˆ€‚¿
  ;; (ef-themes-select 'ef-summer)øˆ€ƒ‘" "ef-sum
  ;; (ef-themes-select 'ef-summer)øˆ€ƒ‘
  (setq ef-themes-to-toggle '(ef-winter ef-summer))øˆ€‚¿" "apply-theme
      (add-hook 'ns-system-appearance-change-functions #'my/apply-theme)øˆ€ƒ£
  (defun my/apply-theme (appearance)øˆ€ƒš" "theme
[[https://protesilaos.com/emacs/ef-themes][ef themes]] æ˜¯æˆ‘éå¸¸å–œæ¬¢çš„ä¸€ä¸ªä¸»é¢˜åŒ…ã€‚øˆ€‚·
(use-package ef-themesøˆ€‚º
  :bind (\"C-c t\" . ef-themes-toggle)øˆ€‚¼
  ;; set two specific themes and switch between themøˆ€‚¾
  (setq ef-themes-to-toggle '(ef-summer ef-winter))øˆ€‚¿
  (setq ef-themes-headingsøˆ€ƒ
  (setq ef-themes-region '(intense no-extend neutral))øˆ€ƒˆ
  ;; Disable all other themes to avoid awkward blending:øˆ€ƒ‰
  (mapc #'disable-theme custom-enabled-themes)øˆ€ƒŠ" "f5
(global-set-key (kbd \"<f5>\") 'open-custom-post-file)øˆ€‚‡" "f9
(global-set-key (kbd \"<f9>\") 'eshell)øˆ€·º" "mail
					(\"#+email:\"         . 128231)       ; ğŸ“§øˆ€’š
							  (\"mail\"     . ?m)øˆ€•¨
         (expand-file-name \"mail.org\" org-directory)øˆ€¢´
  (add-to-list 'mailcap-mime-extensions '(\".mp4\" . \"video/mp4\"))øˆ€®®" "bookmark
                                      (bookmarks . \"bookmark\")øˆ€Šµ
                     \"bookmarks\"øˆ€Œ“
                           (\"b\" \"Bookmarks\" entry (file+headline \"capture.org\" \"Bookmarks\")øˆ€—½
         (\"C-x r b\" . consult-bookmark)            ;; orig. bookmark-jumpøˆ€¦‚
   consult-bookmark consult-recent-file consult-xreføˆ€§
   consult--source-bookmark consult--source-file-registerøˆ€§
         (\"b\"   . dirvish-goto-bookmark)øˆ€®¤
  (dirvish-menu-bookmarks '((\"h\" \"~/\"             \"Home\")øˆ€®¼" "eshell
  (eshell-input-filter 'eshell-input-filter-initial-space)øˆ€·½
  (eshell-error-if-no-glob t)øˆ€·¾
  (eshell-glob-case-insensitive t)øˆ€·¿
  (eshell-rc-script (locate-user-emacs-file \"etc/eshell/profile\"))øˆ€¸
  (eshell-login-script (locate-user-emacs-file \"etc/eshell/login\"))øˆ€¸‚
** eshell alias è®¾ç½®øˆ€¸†
#+BEGIN_SRC text :tangle etc/eshell/aliasesøˆ€¸ˆ
alias up eshell-up $1øˆ€¸
alias pk eshell-up-peek $1øˆ€¸" "f9
         (\"f9\" . eshell)øˆ€·…" "dashb
** Dashboardøˆ€Š¥
  (use-package dashboardøˆ€Š§
      (setq dashboard-banner-logo-title \"Welcome to Emacs Dashboard\")øˆ€Š¬
      (setq dashboard-startup-banner \"~/.emacs.d/logo.png\")øˆ€Š®
      (setq dashboard-center-content t)øˆ€Š°
      (setq dashboard-set-heading-icons t)øˆ€Š±
      (setq dashboard-icon-type 'all-the-icons)øˆ€Š²
      (setq dashboard-set-file-icons t)øˆ€Š³
      (setq dashboard-heading-icons '((recents   . \"history\")øˆ€Š´" "eshell
** eshell åŸºæœ¬é…ç½®øˆ€¶·
(use-package eshelløˆ€¶º
  :functions eshell/aliasøˆ€¶¼
  :hook ((eshell-mode . (lambda ()øˆ€¶½
  (defalias 'eshell/vi 'find-file)øˆ€·
  (defalias 'eshell/vim 'find-file)øˆ€·
  (defun eshell/bat (file)øˆ€·‘
  (defalias 'eshell/cat 'eshell/bat)øˆ€·š
  (defun eshell/z ()øˆ€·" "eshell
  ;; For Eshelløˆ€¨
  ;; avoid press RET twice in Eshelløˆ€¨
    \"Send completion candidate when inside comint/eshell.\"øˆ€¨’
     ((and (derived-mode-p 'eshell-mode) (fboundp 'eshell-send-input))øˆ€¨”
      (eshell-send-input))øˆ€¨•
    ;; for Eshell:øˆ€¨´
** eshell åŸºæœ¬é…ç½®øˆ€¶·
(use-package eshelløˆ€¶º
  :functions eshell/aliasøˆ€¶¼" "eshell-mode
  (add-hook 'eshell-mode-hookøˆ€¨‰
     ((and (derived-mode-p 'eshell-mode) (fboundp 'eshell-send-input))øˆ€¨”
  :hook ((eshell-mode . (lambda ()øˆ€¶½
  :bind (:map eshell-mode-mapøˆ€¸Ÿ
  :hook (eshell-mode . eshell-syntax-highlighting-global-mode)øˆ€¹™
  :hook (eshell-mode . esh-autosuggest-mode)øˆ€¹ª
          \"^\\\\*eshell.*\\\\*$\" eshell-mode ;; eshell as a popupøˆ€‰®" "eshell
                              (eshell          . t)øˆ€œº
  ;; enable corfu in eshelløˆ€¨ˆ
  (add-hook 'eshell-mode-hookøˆ€¨‰
  ;; For Eshelløˆ€¨
  ;; avoid press RET twice in Eshelløˆ€¨
    \"Send completion candidate when inside comint/eshell.\"øˆ€¨’
     ((and (derived-mode-p 'eshell-mode) (fboundp 'eshell-send-input))øˆ€¨”
      (eshell-send-input))øˆ€¨•
    ;; for Eshell:øˆ€¨´" "dashboard
** Dashboardøˆ€Š¥
  (use-package dashboardøˆ€Š§
      (setq dashboard-banner-logo-title \"Welcome to Emacs Dashboard\")øˆ€Š¬
      (setq dashboard-startup-banner \"~/.emacs.d/logo.png\")øˆ€Š®
      (setq dashboard-center-content t)øˆ€Š°
      (setq dashboard-set-heading-icons t)øˆ€Š±
      (setq dashboard-icon-type 'all-the-icons)øˆ€Š²
      (setq dashboard-set-file-icons t)øˆ€Š³
      (setq dashboard-heading-icons '((recents   . \"history\")øˆ€Š´" "company
  (setq orderless-component-separator \"[ &]\") ; & is for company because space will break completionøˆ€¥–
** company-modeøˆ€«‹
(use-package companyøˆ€«
  :init (global-company-mode)øˆ€«
  (setq company-minimum-prefix-length 3) ; åªéœ€æ•² 1 ä¸ªå­—æ¯å°±å¼€å§‹è¿›è¡Œè‡ªåŠ¨è¡¥å…¨øˆ€«‘
  (setq company-tooltip-align-annotations t)øˆ€«’
  (setq company-idle-delay 3)øˆ€«“
  (setq company-show-numbers t) ;; ç»™é€‰é¡¹ç¼–å· (æŒ‰å¿«æ·é”® M-1ã€M-2 ç­‰ç­‰æ¥è¿›è¡Œé€‰æ‹©).øˆ€«”
  (setq company-selection-wrap-around t)øˆ€«•" "eshell
** eshell åŸºæœ¬é…ç½®øˆ€·Š
(use-package eshelløˆ€·
  :functions eshell/aliasøˆ€·
  :hook ((eshell-mode . (lambda ()øˆ€·
  (defalias 'eshell/vi 'find-file)øˆ€· 
  (defalias 'eshell/vim 'find-file)øˆ€·¡
  (defun eshell/bat (file)øˆ€·¤
  (defalias 'eshell/cat 'eshell/bat)øˆ€·­
  (defun eshell/z ()øˆ€·°"))
(setq mark-ring 'nil)
(setq search-ring 'nil)
(setq regexp-search-ring 'nil)
(setq extended-command-history '("auto-package-update-now" "package-list-packages" "comment-line" "org-toggle-inline-images" "org-display-inline-images" "org-insert-link" "comment-region" "package-list-packages" "consult-buffer" #("savehist-mode" 0 13 (ivy-index 1)) #("package-list-packages" 0 21 (ivy-index 1)) #("auto-package-update-now" 0 23 (ivy-index 1)) #("package-refresh-contents" 0 24 (ivy-index 0)) #("restart-emacs" 0 13 (ivy-index 3)) #("ef-themes-select" 0 16 (ivy-index 3)) #("markdown-live-preview-switch-to-output" 0 38 (ivy-index 0)) #("markdown-insert-image" 0 21 (ivy-index 0)) #("rime-select-schema" 0 18 (ivy-index 0)) #("org-download-clipboard" 0 22 (ivy-index 0)) #("rime-mode" 0 9 (ivy-index 0)) #("markdown-edit-code-block" 0 24 (ivy-index 3)) #("markdown-insert-gfm-code-block" 0 30 (ivy-index 2)) #("markdown-toggle-fontify-code-blocks-natively" 0 44 (ivy-index 1)) #("markdown-insert-code" 0 20 (ivy-index 0)) #("markdown-insert-uri" 0 19 (ivy-index 0)) #("eglot" 0 5 (ivy-index 9)) #("pyvenv-workon" 0 13 (ivy-index 5)) #("pyvenv-mode" 0 11 (ivy-index 3)) #("lsp" 0 3 (ivy-index 126)) #("org-time-stamp" 0 14 (ivy-index 1)) #("org-babel-tangle" 0 16 (ivy-index 1)) #("eshell" 0 6 (ivy-index 7)) #("uncomment-region" 0 16 (ivy-index 2)) #("comment-region" 0 14 (ivy-index 1))))
